# -*- coding: utf-8 -*-
"""Model to predict a student's marks based on hours studied.( 2025 - 06 - 27 ).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GnnaID6wdgx3CRFE0ZT9CGQJx5j8r6tm
"""

# Step 1: Import libraries
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt

# Step 2: Create simple data
# Hours studied (X) vs. Marks scored (y)
X = np.array([[2], [4], [6], [8], [10]])   # 2D array for sklearn
y = np.array([50, 65, 80, 90, 95])

model = LinearRegression()
model.fit(X , y)

y_pred = model.predict(X)

mse = mean_squared_error(y, y_pred)
rscore = r2_score(y, y_pred)

print(mse)
print(rscore)

plt.scatter(X , y , color='red' , label='Actual')
plt.plot(X , y_pred , color='purple' ,label='Predicted-Values')
plt.xlabel('Hours Studied')
plt.ylabel('Marks Scored')
plt.title('Linear Regression')
plt.legend()
plt.show()

