# -*- coding: utf-8 -*-
"""GPT-2 Transformer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18KxYb3BMfCwruoZytwts1ptTFtQtqrRr
"""

!pip install transformers

from transformers import (GPT2LMHeadModel , GPT2Tokenizer)

model = GPT2LMHeadModel.from_pretrained('gpt2')
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')

input_text = 'tom holland new movie'

inputs = tokenizer(input_text, return_tensors='pt')

outputs = model.generate(inputs['input_ids'], max_length=150, num_return_sequences=1, no_repeat_ngram_size=2)

g_text = tokenizer.decode(outputs[0] , skip_special_tokens=True)
display(g_text)

