# -*- coding: utf-8 -*-
"""mlp_classifier_neural_networks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GFoLITzkgOub74hoPyxXwPWV0WqhwR7t
"""

from sklearn.neural_network import MLPClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

iris = load_iris()
X, y = iris.data, iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

mlp = MLPClassifier(hidden_layer_sizes=(10, 10), max_iter=1000, random_state=42)
mlp.fit(X_train_scaled, y_train)

accuracy = mlp.score(X_test_scaled, y_test)
print(f"Model accuracy: {accuracy}")

